export const dummyArticleText = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eu dolor ac felis fringilla rutrum. Nullam sit amet scelerisque eros. Donec in imperdiet nibh. Quisque diam sem, vulputate nec diam vitae, sodales mattis mauris. Nunc at leo ac enim dignissim posuere. Ut pulvinar sed enim non malesuada. Proin eu ipsum quis nibh tristique tempus quis ut justo. Integer a imperdiet enim, maximus aliquam lectus. Maecenas accumsan iaculis ex.

Etiam egestas a enim vel aliquam. Vivamus dignissim consequat libero, et euismod augue faucibus et. Nullam metus enim, venenatis sollicitudin est ac, condimentum dapibus erat. Duis mollis et sem interdum egestas. Ut at dui vel augue pharetra molestie sit amet ac eros. Donec nec nunc odio. Maecenas tincidunt elit ex, quis pretium sem pulvinar ac. In volutpat metus est, eget mattis ex gravida quis. Etiam condimentum condimentum lacus. Nunc eget accumsan erat, ac ultrices felis. Suspendisse potenti.

In sit amet dui vitae orci scelerisque sollicitudin. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin eu molestie metus. Nullam facilisis lectus sed fermentum ornare. Aenean sit amet turpis nec est feugiat rutrum. Nam ornare volutpat sem, at malesuada elit porta ut. Aenean in pharetra tortor, a interdum tortor. Aenean eu pharetra justo. Aenean porta accumsan ex et sollicitudin. Pellentesque sed sem eget massa efficitur congue eget cursus urna. Aliquam erat volutpat. Ut ac mollis dolor. Nullam non nulla eget tellus aliquam sollicitudin. Curabitur blandit lectus sed velit semper pulvinar. Aenean odio quam, congue eu varius eget, auctor et enim. Pellentesque sit amet vehicula ligula.

Proin non dui fringilla, imperdiet quam posuere, interdum sem. Ut sollicitudin mi sit amet dui semper, ut consequat lectus interdum. Phasellus tempus ante sit amet diam mollis feugiat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras rhoncus justo sed justo consequat, vitae tempus orci rhoncus. Nullam efficitur diam eros, at egestas erat feugiat vel. Fusce condimentum ullamcorper elit non aliquet. Integer lacinia pellentesque faucibus. Maecenas commodo ex et mauris dictum porta at non diam.

Donec maximus blandit mollis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque hendrerit massa eget pulvinar mattis. Phasellus quis tincidunt enim. Integer porta lorem ut felis accumsan maximus. Pellentesque ac justo commodo, maximus enim quis, iaculis dolor. Maecenas interdum sollicitudin tellus quis scelerisque. Praesent cursus congue urna vitae mollis. Donec ut ex mauris. Proin luctus non arcu at egestas. Vestibulum luctus, lorem dignissim commodo luctus, ante enim commodo arcu, in porta nibh nisi quis turpis. Nullam mattis nunc vel pellentesque iaculis. Mauris auctor, odio a placerat lacinia, lacus lacus malesuada elit, id tempus nisl metus non tellus.

Nunc faucibus odio in nunc bibendum suscipit. Nam faucibus sapien eget interdum semper. Donec rhoncus enim lacus, vel porttitor mauris euismod at. Mauris laoreet lectus sodales turpis rhoncus interdum. Vivamus placerat ipsum vel nibh varius elementum. Nunc quis nibh ac risus scelerisque auctor nec non eros. Aliquam ullamcorper fringilla elit, quis euismod nibh fringilla eu. Praesent pulvinar in urna ut consectetur.

Ut rutrum imperdiet orci. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla facilisi. Cras consequat porta magna vel commodo. Proin dapibus aliquet lorem sed porttitor. Nullam tincidunt tellus vel posuere varius. Vestibulum ac euismod purus. Morbi nibh mi, suscipit eu ullamcorper sed, porta efficitur tortor. Sed convallis vehicula lacus, eget vulputate orci. Nullam in pharetra dui. Nam sollicitudin lorem quis maximus tincidunt. Sed feugiat non nunc at consectetur. Maecenas varius ante vulputate feugiat volutpat. Morbi quis viverra mauris, at consequat enim. Donec condimentum erat at facilisis condimentum. Vivamus vehicula fringilla metus, vel aliquam purus ullamcorper.`;
